// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ActiveOption': string;
  'Option': string;
  'SelectedOption': string;
}
export const cssExports: CssExports;
export default cssExports;
