// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Node': string;
  'ScreenreaderOnly': string;
  'Step': string;
  'StepActive': string;
  'StepComplete': string;
  'StepperContainer': string;
  'VerticalLine': string;
  'VerticalLineComplete': string;
}
export const cssExports: CssExports;
export default cssExports;
