// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CheckboxInput': string;
  'Facade': string;
  'FacadeBorder': string;
  'checkboxWrapper': string;
  'checkboxWrapper2': string;
  'infoIcon': string;
  'label': string;
  'labelWithTooltip': string;
  'popper': string;
  'root': string;
  'root2': string;
  'tooltip': string;
  'tooltipBody': string;
}
export const cssExports: CssExports;
export default cssExports;
