// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accountIcon': string;
  'cta': string;
  'estimateCopy': string;
  'estimateCopyOptimizely': string;
  'flex': string;
  'itemsCenter': string;
  'laptopAndUp': string;
  'laptopAndUpContainer': string;
  'logo': string;
  'navbar': string;
  'navbarWrapper': string;
  'searchIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
