// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Alert': string;
  'Example': string;
  'success': string;
}
export const cssExports: CssExports;
export default cssExports;
