// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LabelClassExample': string;
  'TextClassExample': string;
}
export const cssExports: CssExports;
export default cssExports;
