language: node_js
before_install:
  - echo "@fortawesome:registry=https://npm.fontawesome.com/" > .npmrc
  - echo "//npm.fontawesome.com/:_authToken=\${FONTAWESOME_TOKEN}" >> .npmrc
install:
  - yarn
addons:
  apt:
    packages:
      - libgconf-2-4
install: yarn install --frozen-lockfile
cache:
  yarn: true
  directories:
    - ~/.cache
env:
  - NODE_ENV=ci
script:
  - yarn lint
  - yarn test
  - yarn e2e:ci
after_success:
  - yarn build
