httpTimeout: 600000

nodeLinker: node-modules

npmRegistries:
  //npm.fontawesome.com/:
    npmAlwaysAuth: true
  //npm.pkg.github.com:
    npmAlwaysAuth: true

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
  getethos:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.2.2.cjs
