// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'carrot': string;
  'leftColumn': string;
  'phoneTitle': string;
  'rightColumn': string;
  'root': string;
  'summary': string;
}
export const cssExports: CssExports;
export default cssExports;
