// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Black': string;
  'BlackOutline': string;
  'Button': string;
  'Medium': string;
  'Small': string;
  'Stateful': string;
  'Unstyled': string;
  'White': string;
  'WhiteCTA': string;
  'WhiteOutline': string;
  'arrowIcon': string;
  'arrowIconInline': string;
  'backArrowIconInline': string;
  'fullWidth': string;
  'isSelected': string;
}
export const cssExports: CssExports;
export default cssExports;
