// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'iconDefault': string;
  'iconDown': string;
  'iconUp': string;
}
export const cssExports: CssExports;
export default cssExports;
