// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accountIcon': string;
  'blockNavbar': string;
  'cta': string;
  'ctaButton': string;
  'flex': string;
  'hamburger': string;
  'hideMobileMenu': string;
  'itemsCenter': string;
  'laptopAndUp': string;
  'logo': string;
  'mobileMenu': string;
  'navLink': string;
  'navbar': string;
  'phoneLogo': string;
  'phoneLogoFancy': string;
  'phoneOnly': string;
  'searchIcon': string;
  'tabletAndUp': string;
  'tabletAndUpContainer': string;
  'textLink': string;
}
export const cssExports: CssExports;
export default cssExports;
