// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'ButtonLeft': string;
  'ButtonRight': string;
  'Disabled': string;
  'Input': string;
  'InputLeft': string;
  'InputRight': string;
  'NoraButtonInputContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
