// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'root': string;
  'section': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
