// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Container': string;
  'Layout': string;
}
export const cssExports: CssExports;
export default cssExports;
