// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'RadioButton': string;
  'RadioButtonGroup': string;
}
export const cssExports: CssExports;
export default cssExports;
