// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SearchIcon': string;
  'SearchIconCompact': string;
  'SearchInputCompact': string;
  'SearchInputContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
