// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ModalContent': string;
  'ModalWrapper': string;
  'ModalWrapperActive': string;
}
export const cssExports: CssExports;
export default cssExports;
