// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Resize': string;
  'TextAreaInput': string;
}
export const cssExports: CssExports;
export default cssExports;
