export { TitleSmall2 } from './TitleSmall2.js'
// export { TitleMedium } from './TitleMedium.js'
// export { TitleLarge } from './TitleLarge.js'
// export { TitleXLarge } from './TitleXLarge.js'
// export { TitleXXLarge } from './TitleXXLarge.js'
