export { TitleSmall2 } from './TitleSmall2.js'
export { TitleMedium2 } from './TitleMedium2.js'
export { TitleLarge2 } from './TitleLarge2.js'
export { TitleXLarge2 } from './TitleXLarge2.js'
// export { TitleXXLarge } from './TitleXXLarge.js'
