// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Alert': string;
  'InfoMessage': string;
  'error': string;
  'info': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
