// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Bottom': string;
  'Container': string;
  'DrawerWrapper': string;
  'DrawerWrapperActive': string;
  'DrawerWrapperLocked': string;
  'Horizontals': string;
  'Left': string;
  'Open': string;
  'Right': string;
  'Sidebars': string;
  'Top': string;
}
export const cssExports: CssExports;
export default cssExports;
