// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Inherit': string;
  'Link': string;
}
export const cssExports: CssExports;
export default cssExports;
