// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'DemoCol': string;
  'Field': string;
}
export const cssExports: CssExports;
export default cssExports;
