// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'accordionChild': string;
  'accordionChildren': string;
  'accordionItem': string;
  'accordionParent': string;
  'active': string;
}
export const cssExports: CssExports;
export default cssExports;
