// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'hamburger': string;
  'hideMobileMenu': string;
  'logo': string;
  'mobileMenu': string;
  'mobileNavbar': string;
  'phoneLogo': string;
  'phoneLogoFancy': string;
  'secondaryLinks': string;
  'visible': string;
}
export const cssExports: CssExports;
export default cssExports;
