// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'secondaryLinks': string;
  'secondaryLinksItem': string;
}
export const cssExports: CssExports;
export default cssExports;
