// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'child': string;
  'children': string;
  'childrenColumn': string;
  'childrenCta': string;
  'childrenInner': string;
  'childrenItems': string;
}
export const cssExports: CssExports;
export default cssExports;
