// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'children': string;
  'dropdownNav': string;
  'dropdownNavParent': string;
  'parentIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
