// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Cyan': string;
  'Default': string;
  'Green': string;
  'Neutral': string;
  'Orange': string;
  'Red': string;
  'Tag': string;
}
export const cssExports: CssExports;
export default cssExports;
