// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Active': string;
  'Completed': string;
  'Error': string;
  'Icon': string;
  'IconLinkContainer': string;
  'IconLinkContainerRight': string;
  'LinkAdjusted': string;
  'LinkLeft': string;
  'LinkRight': string;
  'Waived': string;
}
export const cssExports: CssExports;
export default cssExports;
