// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CustomTipExample': string;
  'basicExample': string;
  'centeredExample': string;
  'flipExample': string;
  'overflowHidden': string;
  'staticOuterDiv': string;
}
export const cssExports: CssExports;
export default cssExports;
