// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'block': string;
  'closeButton': string;
  'hidden': string;
  'icon': string;
  'inline': string;
  'label': string;
  'mobileModal': string;
  'noTransition': string;
  'popperContainer': string;
  'popperContentBox': string;
  'root': string;
  'visible': string;
}
export const cssExports: CssExports;
export default cssExports;
