// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Animatable': string;
  'Bottom': string;
  'CustomButton': string;
  'Left': string;
  'Open': string;
  'Right': string;
  'SnackbarContainer': string;
  'SnackbarSkin': string;
  'ZoomInUp': string;
  'zoomInUp': string;
}
export const cssExports: CssExports;
export default cssExports;
