// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AllCaps': string;
  'Body': string;
  'Body2': string;
  'Book500': string;
  'BrandForest': string;
  'BrandSalamander': string;
  'Cambon': string;
  'Capitalize': string;
  'Caption': string;
  'Caption2': string;
  'Centered': string;
  'Demi600': string;
  'Footnote': string;
  'GrayPrimary': string;
  'GraySecondary': string;
  'GrayStrokeAndDisabled': string;
  'Light300': string;
  'Medium500': string;
  'Regular400': string;
  'Theinhardt': string;
  'TitleLarge': string;
  'TitleLarge2': string;
  'TitleMedium': string;
  'TitleMedium2': string;
  'TitleSmall': string;
  'TitleSmall2': string;
  'TitleXLarge': string;
  'TitleXLarge2': string;
  'TitleXXLarge': string;
  'White': string;
}
export const cssExports: CssExports;
export default cssExports;
