// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Label': string;
  'Panel': string;
  'Toggle': string;
}
export const cssExports: CssExports;
export default cssExports;
