// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Close': string;
  'Header': string;
  'NoraDrawer': string;
}
export const cssExports: CssExports;
export default cssExports;
