name: Build and Deploy

on:
  push:
    # branches:
    #   - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Install dependencies
        run: yarn install --production=false
      - name: Download fonts
        uses: actions/aws/cli@master
        with:
          args: s3 cp s3://eds.ethoslabs.io/fonts.zip ${GITHUB_WORKSPACE}/bin/fonts.zip --profile ci-user
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CONFIG_FILE: ${GITHUB_WORKSPACE}/.aws/config
      - name: Unzip fonts
        run: unzip -o ${GITHUB_WORKSPACE}/bin/fonts.zip -d ${GITHUB_WORKSPACE}/src/
      - name: Build styleguide
        run: yarn styleguide:build
      - name: Archive Build result
        uses: actions/upload-artifact@master
        with:
          name: styleguide
          path: styleguide

  deploy:
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Download build files
        uses: actions/download-artifact@master
        with:
          name: styleguide
      - name: Sync to S3
        uses: actions/aws/cli@master
        args: s3 sync ${GITHUB_WORKSPACE}/styleguide s3://eds.ethoslabs.io/ --delete --exclude fonts.zip --profile ci-user
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CONFIG_FILE: ${GITHUB_WORKSPACE}/.aws/config
