# Test comment
name: Build and Deploy

on:
  push:
    # branches:
    #   - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Run build and deploy script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CONFIG_FILE: $GITHUB_WORKSPACE/.aws/config
        run: |
          echo $AWS_CONFIG_FILE
          ./bin/deploy.sh # might be better to re-write ./bin/deploy.sh as a workflow
