# Test comment
name: Build and Deploy

on:
  push:
    # branches:
    #   - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - run: ./bin/deploy.sh
