# Test comment
name: Build and Deploy

on:
  push:
  pull_request:
    types: [closed]
    # branches:
    #   - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push'
        run: echo "Pushed commit"
      - if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
        run: echo "PR ${{ github.event.pull_request.number }} closed"
      - if: github.event.pull_request.merged == true
        run: echo "PR ${{ github.event.pull_request.number }} merged"
